export const ROUTES = {
  LANDING_SCREEN: 'LANDING_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  MAP_SCREEN: 'MAP_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  DESTINATION_DETAILS_SCREEN: 'DESTINATION_DETAILS_SCREEN',
};
